{{- if and .Values.enabled .Values.service.autoScaler.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.service.autoScaler.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "translator.name" .}}
    chart: {{ template "translator.chart" .}}
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: translator
  minReplicas: {{ .Values.service.autoScaler.minAvailablePods }}
  maxReplicas: {{ .Values.service.autoScaler.maxAvailablePods }}

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
{{- end }}
