{{- if .Values.textanalytics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-analytics
  namespace: {{ .Release.Namespace }}
  labels:
    app: text-analytics
    chart: {{ template "textAnalytics.chart" .}}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.textanalytics.service.autoScaler.minAvailablePods }}
  selector:
    matchLabels:
      app: text-analytics
  template:
    metadata:
      labels:
        app: text-analytics
    spec:
      containers:
        - name: text-analytics-container
          image: {{ template "image.full" .Values.textanalytics.image }}
          imagePullPolicy: {{ template "image.pull" .Values.textanalytics.image }}
          {{- include "image.args" .Values.textanalytics.image.args | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.textanalytics.service.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.textanalytics.service.containerPort }}
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /status
              port: {{ .Values.textanalytics.service.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 5
          {{- include "textanalytics.image.resources" .Values | nindent 10 }}
      imagePullSecrets:
        {{ template "image.secrets" .Values.textanalytics.image.pullSecrets }}
{{- end }}
