{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: text-analytics
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app: text-analytics
    chart: {{ template "textAnalytics.chart" .}}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: text-analytics
{{- end }}
