{{- if .Values.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.name}}
    namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: {{ .Values.storageClassName }}
    resources:
        requests:
            storage: {{ .Values.storage }}
{{- end}}