enabled: false
image:
  registry: mcr.microsoft.com
  repository: azure-cognitive-services/textanalytics/sentiment
  tag: 3.0-en
  # A list of secrets used to pull docker image
  pullSecrets:

  # eula, billing and apikey are required args that user should provide valid values.
  args:
    # Indicates that you've accepted the license for the container.
    # The value of this option must be: accept.
    eula:
    # This is used for specify billing endpoint URI for Text Analytics Service
    # The billing endpoint URI value is available on the Azure portal's Text Analytics Overview page.
    billing:
    # The API key of the Cognitive Service resource used to track billing information.
    # The value of this option must be set to an API key for the provisioned resource specified in Billing.
    apikey:

  # pullByHash default is false.
  # If want to pull docker image by hash, add below two lines:
  #
  # hash: "<image_hash_value>"
  # pullByHash: true
  #
  hash:
  pullByHash: false

# Default computing resource settings for text analytics
cpuRequest: 3000m
cpuLimit: 8000m
memoryRequest: 3Gi
memoryLimit: 8Gi

agentpool: agentpool

service:
  # URI suffix for sentiment analysis, the whole URI is in format "http://<service>:<port>/<sentimentURISuffix>".
  sentimentURISuffix: text/analytics/v3.0/sentiment
  type: LoadBalancer
  port: 50085             # The port Text Analytics service exposed to.
  containerPort: 5000     # Don't change, fixed port number.

  # Users can put annotations on service.yaml as they want
  annotations: {}
  autoScaler:
    enabled: true
    name: text-analytics-autoscaler

    minAvailablePods: 2
    maxAvailablePods: 5

  podDisruption:
    enabled: true
    name: text-analytics-poddisruptionbudget

    maxUnavailable: 20%